# Project information
site_name: 'MentorSoft Manual'
site_description: 'K&M SISTEMAS DE GESTÃO'
site_author: 'KM Sistemas'
#site_url: 'http://manual-mentorsoft.kmsistemas.com.br'
site_url: 'https://manual-mentorsoft.disqus.com'

# Repository
#repo_name: 'KmSistemas/mentorsoft-manual'
#repo_url: 'https://github.com/KmSistemas/mentorsoft-manual'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 K&M Sistemas'

# Configuration
theme:
  name: 'material'

  # https://squidfunk.github.io/mkdocs-material/customization/
  custom_dir: 'custom_theme'
  logo: 'img/logo.png'
  favicon: 'assets/images/favicon.ico'
  language: 'pt'
  palette:
    primary: 'green'
    accent: 'light green'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  feature:
    tabs: true

# Customization
extra:
  social:
    - type: 'facebook'
      link: 'https://www.facebook.com/kmsistemas.br'
    - type: 'google-plus'
      link: 'https://plus.google.com/u/0/+KmSistemasBrApucarana'
  disqus: 'manual-mentorsoft'

#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

# Extensions
markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - admonition

  # https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
  - codehilite

  # https://squidfunk.github.io/mkdocs-material/extensions/footnotes/
  - footnotes

  # https://squidfunk.github.io/mkdocs-material/extensions/metadata/
  - meta

  # https://squidfunk.github.io/mkdocs-material/extensions/permalinks/
  - toc:
      #permalink: true
      permalink: '«'

  - markdown_include.include:
        base_path: docs

  # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
  #- pymdownx.arithmatex
  #- pymdownx.betterem:
  #    smart_enable: all
  #- pymdownx.caret
  #- pymdownx.critic
  #- pymdownx.details
  #- pymdownx.emoji:
  #    emoji_generator: !!python/name:pymdownx.emoji.to_svg
  #- pymdownx.inlinehilite
  #- pymdownx.magiclink
  #- pymdownx.mark
  #- pymdownx.smartsymbols
  #- pymdownx.superfences
  #- pymdownx.tasklist:
  #    custom_checkbox: true
  #- pymdownx.tilde

# Pages
pages:
  - Início: index.md
  - Comercial:
    - 'Inicio': 'modulos/comercial/index.md'
    - Cadastros:
      - 'Cliente': 'modulos/comercial/cadastro/cadastro-cliente.md'
      - 'Representante': 'comum/cadastro-representante.md'
      - 'Fornecedor': 'comum/cadastro-fornecedor.md'
      - 'Tipo de Pedido': 'comum/cadastro-tipo-pedido.md'
      - 'Condição Pagamento': 'comum/cadastro-condicao-pagamento.md'
      - 'Produtos': 'comum/cadastro-produto.md'
      - 'Tipo Despesa/Receita': 'modulos/comercial/cadastro/cadastro-tipo-despesa-receita.md'
      - 'Embalagens': 'comum/cadastro-embalagens.md'
    - Movimentos:
      - 'Comunicação com Cliente': 'modulos/comercial/movimentos/comunicacao-com-clientes.md'
      - 'Pedidos': 'modulos/comercial/movimentos/inserir-pedidos.md'
  - Estoque:
    - 'Inicio': 'modulos/estoque/index.md'
    - Cadastros:
      - 'Produtos': 'comum/cadastro-produto.md'
      - 'Fornecedor': 'comum/cadastro-fornecedor.md'
      - 'Embalagens': 'comum/cadastro-embalagens.md'
      - 'Inventário': 'modulos/estoque/movimentos/inventario.md'
    - Movimentos:
      - 'Entrada por Nota Fiscal': 'comum/entrada-por-nota-fiscal.md'
      - 'Solicitação de Compra': 'modulos/estoque/movimentos/solicitacao-compra.md'
      - 'Romaneio de Faturamento': 'modulos/estoque/movimentos/romaneio-faturamento.md'
      - 'Código de Barras': 'modulos/estoque/movimentos/codigo-barras.md'
  - Faturamento:
    - 'Inicio': 'modulos/faturamento/index.md'
    - Cadastro:
      - 'Cliente': 'comum/cadastro-cliente.md'
      - 'Fornecedor': 'comum/cadastro-fornecedor.md'
      - 'Cadastro CEST': 'comum/cadastro-cest.md'
      - 'Cadastro Tributação': 'comum/cadastro-tributacao.md'
    - Movimentos:
      - 'Abertura de Faturamento': 'modulos/faturamento/movimentos/abertura-faturamento.md'
      - 'Entrada por Nota Fiscal': 'comum/entrada-por-nota-fiscal.md'
      - 'Nota Fiscal Eletronica': 'modulos/faturamento/movimentos/nota-fiscal-eletronica.md'
      - 'Pedidos': 'modulos/comercial/movimentos/inserir-pedidos.md'
  - Industrial:
    - 'Industrial': 'modulos/industrial/index.md'
  - GRH:
    - 'GRH': 'modulos/grh/index.md'
  - Pagar:
    - 'Inicio': 'modulos/pagar/index.md'
    - Cadastros:
      - 'Fornecedor': 'comum/cadastro-fornecedor.md'
    - Movimentos:
      - 'Operação de Pagamento': 'modulos/pagar/movimentos/operacao-pagamento.md'
      - 'Manutenção Parcelas a Pagar': 'modulos/pagar/movimentos/manutencao-parcelas-pagar.md'
      - 'Adiantamento de Fornecedores': 'modulos/pagar/movimentos/adiantamento-fornecedor.md'
  - Receber:
    - 'Inicio': 'modulos/receber/index.md'
    - Cadastros:
      - 'Cliente': 'comum/cadastro-cliente.md'
    - Movimentos:
      - 'Operação de Recebimento': 'modulos/receber/movimentos/operacao-recebimento.md'
  - Tesouraria:
    - 'Tesouraria': 'modulos/tesouraria/index.md'

  - Suporte:
    - 'Instalacao': 'instalacao.md'
    - NFBR:
      - 'Tela de Login': 'nfbr/cadastro/nfbr-tela-login.md'
      - 'Cadastro de Produto': 'nfbr/cadastro/nfbr-cadastro-produtos.md'
